// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blog_ca_nhan.Data;

#nullable disable

namespace blog_ca_nhan.Migrations
{
    [DbContext(typeof(PremiumBlogDbContext))]
    [Migration("20260318070746_AddUserSocialLinks")]
    partial class AddUserSocialLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PostLike", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "UserId")
                        .HasName("PK__PostLike__7B6AECDCEEF5984A");

                    b.HasIndex("UserId");

                    b.ToTable("PostLikes", (string)null);
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "TagId")
                        .HasName("PK__PostTags__7C45AF8257F0EE4C");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags", (string)null);
                });

            modelBuilder.Entity("blog_ca_nhan.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BlogId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__AuditLog__3214EC073B28872F");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CurrentThemeId")
                        .HasColumnType("int");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Blogs__3214EC075B726B94");

                    b.HasIndex("CurrentThemeId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlanId");

                    b.HasIndex(new[] { "Subdomain" }, "UQ__Blogs__AD95567DDD750F85")
                        .IsUnique();

                    b.HasIndex(new[] { "CustomDomain" }, "UQ__Blogs__C4BCD080FF6ACAE6")
                        .IsUnique()
                        .HasFilter("[CustomDomain] IS NOT NULL");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.BlogThemeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OptionValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__BlogThem__3214EC07D773D403");

                    b.HasIndex("BlogId");

                    b.HasIndex("ThemeId");

                    b.ToTable("BlogThemeOptions");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.BlogUser", b =>
                {
                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BlogId", "UserId")
                        .HasName("PK__BlogUser__854F12F447F048EE");

                    b.HasIndex("UserId");

                    b.ToTable("BlogUsers");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07A7CDBF7C");

                    b.HasIndex("BlogId");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Comments__3214EC0720DB8592");

                    b.HasIndex("BlogId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Medium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Media__3214EC0791F5C6EB");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.PlatformSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key")
                        .HasName("PK__Platform__C41E02882A612884");

                    b.ToTable("PlatformSettings");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FeaturedImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__Posts__3214EC071FAEAC51");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BlogId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.PostMetum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MetaKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MetaValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PostMeta__3214EC07B308B393");

                    b.HasIndex("PostId");

                    b.ToTable("PostMeta");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__Subscrib__3214EC07A18B4E36");

                    b.HasIndex("BlogId");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("HasAdFree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("HasCustomDomain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaxPosts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(-1);

                    b.Property<long?>("MaxStorageMb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(100L)
                        .HasColumnName("MaxStorageMB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id")
                        .HasName("PK__Subscrip__3214EC078F30A611");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Tags__3214EC074026FE67");

                    b.HasIndex("BlogId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreviewImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Themes__3214EC0780EA44BC");

                    b.HasIndex(new[] { "CodeName" }, "UQ__Themes__404488D5B7C9B352")
                        .IsUnique();

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DiscordUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsPlatformAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07622D3F27");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4C358708A")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534DD0219EB")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PostLike", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PostLikes__PostI__7A672E12");

                    b.HasOne("blog_ca_nhan.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PostLikes__UserI__7B5B524B");
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PostTags__PostId__6B24EA82");

                    b.HasOne("blog_ca_nhan.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK__PostTags__TagId__6C190EBB");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.AuditLog", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Blog", "Blog")
                        .WithMany("AuditLogs")
                        .HasForeignKey("BlogId")
                        .HasConstraintName("FK__AuditLogs__BlogI__02084FDA");

                    b.HasOne("blog_ca_nhan.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__AuditLogs__UserI__02FC7413");

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Blog", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Theme", "CurrentTheme")
                        .WithMany("Blogs")
                        .HasForeignKey("CurrentThemeId")
                        .IsRequired()
                        .HasConstraintName("FK__Blogs__CurrentTh__4E88ABD4");

                    b.HasOne("blog_ca_nhan.Models.User", "Owner")
                        .WithMany("Blogs")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__Blogs__OwnerId__4D94879B");

                    b.HasOne("blog_ca_nhan.Models.SubscriptionPlan", "Plan")
                        .WithMany("Blogs")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK__Blogs__PlanId__4F7CD00D");

                    b.Navigation("CurrentTheme");

                    b.Navigation("Owner");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.BlogThemeOption", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Blog", "Blog")
                        .WithMany("BlogThemeOptions")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BlogTheme__BlogI__7E37BEF6");

                    b.HasOne("blog_ca_nhan.Models.Theme", "Theme")
                        .WithMany("BlogThemeOptions")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BlogTheme__Theme__7F2BE32F");

                    b.Navigation("Blog");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.BlogUser", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Blog", "Blog")
                        .WithMany("BlogUsers")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BlogUsers__BlogI__5441852A");

                    b.HasOne("blog_ca_nhan.Models.User", "User")
                        .WithMany("BlogUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BlogUsers__UserI__5535A963");

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Category", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Blog", "Blog")
                        .WithMany("Categories")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Categorie__BlogI__5812160E");

                    b.HasOne("blog_ca_nhan.Models.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__Categorie__Paren__59063A47");

                    b.Navigation("Blog");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Comment", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Blog", "Blog")
                        .WithMany("Comments")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Comments__BlogId__73BA3083");

                    b.HasOne("blog_ca_nhan.Models.Comment", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__Comments__Parent__75A278F5");

                    b.HasOne("blog_ca_nhan.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__Comments__PostId__74AE54BC");

                    b.Navigation("Blog");

                    b.Navigation("Parent");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Medium", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Blog", "Blog")
                        .WithMany("Media")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Media__BlogId__6EF57B66");

                    b.HasOne("blog_ca_nhan.Models.User", "User")
                        .WithMany("Media")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Media__UserId__6FE99F9F");

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Post", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__Posts__AuthorId__5DCAEF64");

                    b.HasOne("blog_ca_nhan.Models.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Posts__BlogId__5CD6CB2B");

                    b.HasOne("blog_ca_nhan.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Posts__CategoryI__5EBF139D");

                    b.Navigation("Author");

                    b.Navigation("Blog");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.PostMetum", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Post", "Post")
                        .WithMany("PostMeta")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PostMeta__PostId__656C112C");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Subscriber", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Blog", "Blog")
                        .WithMany("Subscribers")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Subscribe__BlogI__06CD04F7");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Tag", b =>
                {
                    b.HasOne("blog_ca_nhan.Models.Blog", "Blog")
                        .WithMany("Tags")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tags__BlogId__68487DD7");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Blog", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BlogThemeOptions");

                    b.Navigation("BlogUsers");

                    b.Navigation("Categories");

                    b.Navigation("Comments");

                    b.Navigation("Media");

                    b.Navigation("Posts");

                    b.Navigation("Subscribers");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Category", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Comment", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostMeta");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.Theme", b =>
                {
                    b.Navigation("BlogThemeOptions");

                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("blog_ca_nhan.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BlogUsers");

                    b.Navigation("Blogs");

                    b.Navigation("Media");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
